[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
  
[[redirects]]
  from = "/"
    to = "https://exclamationbark.com/"
      status = 301

[[redirects]]
  from = "https://drowsyseal.com*"
  to = "https://exclamationbark.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.drowsyseal.com*"
  to = "https://exclamationbark.com/:splat"
  status = 301
  force = true
